AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Quiz Backend with API Gateway, Lambda, DynamoDB, and JWT Auth

Parameters:
  SecretKey:
    Type: String
    Description: Secret key used for JWT authentication

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11

Resources:

  QuizApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,GET,POST'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: JWTAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          JWTAuthorizer:
            FunctionArn: !GetAtt JWTAuthorizerFunction.Arn
            Identity:
              Header: Authorization

  JWTAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: jwt_authorizer/
      Handler: app.lambda_handler
      Environment:
        Variables:
          SECRET_KEY: !Ref SecretKey
      Runtime: python3.11

  StartQuizFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: start_quiz/
      Handler: app.lambda_handler
      Events:
        GetQuestions:
          Type: Api
          Properties:
            Path: /start-quiz
            Method: get
            RestApiId: !Ref QuizApi
            Auth:
              Authorizer: JWTAuthorizer

  SubmitAnswerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: submit_answer/
      Handler: app.lambda_handler
      Events:
        Submit:
          Type: Api
          Properties:
            Path: /submit-answer
            Method: post
            RestApiId: !Ref QuizApi
            Auth:
              Authorizer: JWTAuthorizer


  GetAnswers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_answers/
      Handler: app.lambda_handler
      Events:
        GetAnswersAPI:
          Type: Api
          Properties:
            Path: /get-answer
            Method: GET
            RestApiId: !Ref QuizApi
            Auth:
              Authorizer: JWTAuthorizer

  UserAttemptsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_attempts/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: QuizAttempts
      Environment:
        Variables:
          QUIZ_ATTEMPTS_TABLE: QuizAttempts
          SECRET_KEY: !Ref SecretKey
      Events:
        UserAttemptsGet:
          Type: Api
          Properties:
            Path: /user/attempts
            Method: get
            RestApiId: !Ref QuizApi
            Auth:
              Authorizer: JWTAuthorizer
        UserAttemptsPost:
          Type: Api
          Properties:
            Path: /user/attempts
            Method: post
            RestApiId: !Ref QuizApi
            Auth:
              Authorizer: JWTAuthorizer

  CheckAttemptsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: check_attempts/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: QuizAttempts
      Environment:
        Variables:
          QUIZ_ATTEMPTS_TABLE: QuizAttempts
          SECRET_KEY: !Ref SecretKey
      Events:
        CheckAttemptsAPI:
          Type: Api
          Properties:
            Path: /check-attempts
            Method: get
            RestApiId: !Ref QuizApi
            Auth:
              Authorizer: JWTAuthorizer

  SubmitQuizFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: submit_quiz/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: QuizAttempts
      Environment:
        Variables:
          QUIZ_ATTEMPTS_TABLE: QuizAttempts
      Events:
        SubmitQuizAPI:
          Type: Api
          Properties:
            Path: /submit-quiz
            Method: post
            RestApiId: !Ref QuizApi
            Auth:
              Authorizer: JWTAuthorizer

  LeaderboardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: leaderboard/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: QuizAttempts
        - DynamoDBReadPolicy:
            TableName: Users
      Environment:
        Variables:
          QUIZ_ATTEMPTS_TABLE: QuizAttempts
      Events:
        LeaderboardAPI:
          Type: Api
          Properties:
            Path: /leaderboard
            Method: get
            RestApiId: !Ref QuizApi

  UserLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_login/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: Users
      Environment:
        Variables:
          SECRET_KEY: !Ref SecretKey
      Events:
        UserLoginAPI:
          Type: Api
          Properties:
            Path: /login
            Method: post
            RestApiId: !Ref QuizApi

  UserSignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_signup/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Users
      Environment:
        Variables:
          SECRET_KEY: !Ref SecretKey
      Events:
        UserSignupAPI:
          Type: Api
          Properties:
            Path: /signup
            Method: post
            RestApiId: !Ref QuizApi

  RequestPasswordResetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: request_password_reset/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: Users
      Environment:
        Variables:
          SECRET_KEY: !Ref SecretKey
      Events:
        RequestPasswordResetAPI:
          Type: Api
          Properties:
            Path: /request-password-reset
            Method: post
            RestApiId: !Ref QuizApi

  ResetPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: reset_password/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Users
      Environment:
        Variables:
          SECRET_KEY: !Ref SecretKey
      Events:
        ResetPasswordAPI:
          Type: Api
          Properties:
            Path: /reset-password
            Method: post
            RestApiId: !Ref QuizApi

  CheckUserExistsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: check_user_exists/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: Users
      Events:
        CheckUserExistsAPI:
          Type: Api
          Properties:
            Path: /check-user-exists
            Method: post
            RestApiId: !Ref QuizApi

  GoogleAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: google_auth/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Users
      Environment:
        Variables:
          GOOGLE_CLIENT_ID: ""
          SECRET_KEY: !Ref SecretKey
      Events:
        GoogleAuthAPI:
          Type: Api
          Properties:
            Path: /auth/google
            Method: post
            RestApiId: !Ref QuizApi

Outputs:
  QuizApiUrl:
    Description: "API Gateway endpoint URL for Quiz API"
    Value: !Sub "https://${QuizApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: !Sub "${AWS::StackName}-QuizApiUrl"

  QuizAttemptsTableName:
    Description: "DynamoDB table name for quiz attempts (existing table)"
    Value: QuizAttempts
    Export:
      Name: !Sub "${AWS::StackName}-QuizAttemptsTableName"
